export const INDIAN_CITIES = [
  'Jaipur',
  'Udaipur',
  'Jodhpur',
  'Kota',
  'Ajmer',
  'Bikaner',
  'Alwar',
  'Bharatpur',
  'Sikar',
  'Pali',
  'Tonk',
  'Sawai Madhopur',
  'Bhilwara',
  'Nagaur',
  'Chittorgarh',
  'Jhunjhunu',
  'Dausa',
  'Karauli',
  'Dholpur',
  'Baran',
  'Jaisalmer',
  'Barmer',
  'Jalore',
  'Sirohi',
  'Dungarpur',
  'Banswara',
  'Pratapgarh',
  'Rajsamand',
  'Bundi',
  'Agra',
  'Varanasi',
  'Lucknow',
  'Kanpur',
  'Prayagraj',
  'Gorakhpur',
  'Meerut',
  'Bareilly',
  'Aligarh',
  'Moradabad',
  'Saharanpur',
  'Noida',
  'Ghaziabad',
  'Firozabad',
  'Jhansi',
  'Muzaffarnagar',
  'Mathura',
  'Shahjahanpur',
  'Ayodhya',
  'Rampur',
  'Hapur',
  'Etawah',
  'Mirzapur',
  'Bulandshahr',
  'Sambhal',
  'Amroha',
  'Hardoi',
  'Farrukhabad',
  'Unnao',
  'Sitapur',
  'Lakhimpur',
  'Faizabad',
  'Gonda',
  'Bahraich',
  'Basti',
  'Deoria',
  'Ballia',
  'Azamgarh',
  'Mau',
  'Jaunpur',
  'Ghazipur',
  'Chandauli',
  'Bhadohi',
  'Sonbhadra',
  'Maharajganj',
  'Kushinagar',
  'Siddharthnagar',
  'Sant Kabir Nagar',
  'Ambedkar Nagar',
  'Amethi',
  'Hathras',
  'Kasganj',
  'Shamli',
  'Baghpat',
  'Indore',
  'Bhopal',
  'Jabalpur',
  'Gwalior',
  'Ujjain',
  'Sagar',
  'Ratlam',
  'Satna',
  'Rewa',
  'Murwara',
  'Singrauli',
  'Burhanpur',
  'Khandwa',
  'Bhind',
  'Mandsaur',
  'Neemuch',
  'Vidisha',
  'Hoshangabad',
  'Sehore',
  'Betul',
  'Chhindwara',
  'Damoh',
  'Katni',
  'Shivpuri',
  'Morena',
  'Datia',
  'Guna',
  'Ashoknagar',
  'Alirajpur',
  'Anuppur',
  'Balaghat',
  'Barwani',
  'Chhatarpur',
  'Dhar',
  'Dindori',
  'Jhabua',
  'Mandla',
  'Narsinghpur',
  'Niwari',
  'Panna',
  'Raisen',
  'Rajgarh',
  'Seoni',
  'Shahdol',
  'Sheopur',
  'Shajapur',
  'Sidhi',
  'Tikamgarh',
  'Umaria',
] as const;

export const INDIAN_STATES = [
  'Rajasthan',
  'Uttar Pradesh',
  'Madhya Pradesh',
  'Maharashtra',
  'Gujarat',
  'Karnataka',
  'Tamil Nadu',
  'Andhra Pradesh',
  'Telangana',
  'Kerala',
  'West Bengal',
  'Odisha',
  'Bihar',
  'Jharkhand',
  'Punjab',
  'Haryana',
  'Himachal Pradesh',
  'Uttarakhand',
  'Assam',
  'Chhattisgarh',
] as const;

export const PROPERTY_TYPES = [
  { value: 'ENTIRE_HOME', label: 'Entire Home' },
  { value: 'PRIVATE_ROOM', label: 'Private Room' },
  { value: 'SHARED_ROOM', label: 'Shared Room' },
  { value: 'GUEST_HOUSE', label: 'Guest House' },
  { value: 'HOMESTAY', label: 'Homestay' },
] as const;

export const STAY_PURPOSES = [
  { value: 'TOURISM', label: 'Tourism' },
  { value: 'HOSPITAL_VISIT', label: 'Hospital Visit' },
  { value: 'EMERGENCY', label: 'Emergency' },
  { value: 'EXAM', label: 'Exam' },
  { value: 'WEDDING', label: 'Wedding' },
  { value: 'PILGRIMAGE', label: 'Pilgrimage' },
  { value: 'BUSINESS', label: 'Business' },
  { value: 'FAMILY_VISIT', label: 'Family Visit' },
  { value: 'OTHER', label: 'Other' },
] as const;

export const EMERGENCY_REASONS = [
  { value: 'HOSPITAL', label: 'Hospital' },
  { value: 'FAMILY_EMERGENCY', label: 'Family Emergency' },
  { value: 'UNEXPECTED_TRAVEL', label: 'Unexpected Travel' },
  { value: 'OTHER', label: 'Other' },
] as const;

export const COMMON_AMENITIES = [
  'WiFi',
  'Air Conditioning',
  'Heating',
  'Kitchen',
  'Washing Machine',
  'TV',
  'Parking',
  'Hot Water',
  'Refrigerator',
  'Microwave',
  'Iron',
  'Hair Dryer',
  'Essentials (towels, bed sheets, soap)',
  'Workspace',
  'Crib',
  'High Chair',
  'Fire Extinguisher',
  'Smoke Alarm',
  'Carbon Monoxide Alarm',
  'First Aid Kit',
  'Security Cameras',
  'Lock on Bedroom Door',
  'Private Entrance',
  'Balcony',
  'Garden',
  'Pool',
  'Gym',
  'Elevator',
  'Wheelchair Accessible',
] as const;

export const CURRENCY = {
  code: 'INR',
  symbol: '₹',
  locale: 'en-IN',
} as const;

export const DATE_FORMAT = 'YYYY-MM-DD';
export const DATETIME_FORMAT = 'YYYY-MM-DD HH:mm';

export const PAGINATION = {
  defaultPage: 1,
  defaultLimit: 12,
  maxLimit: 50,
} as const;

export const PRICE_RANGE = {
  min: 500,
  max: 10000,
  step: 500,
} as const;

export const GUEST_LIMITS = {
  min: 1,
  max: 10,
} as const;

export const REQUIRED_NIGHTS = {
  min: 1,
  max: 30,
} as const;

export const RATING = {
  min: 1,
  max: 5,
} as const;

export const VERIFICATION_BADGES = {
  VERIFIED: 'verified',
  SUPERHOST: 'superhost',
  NEW: 'new',
} as const;