"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VERIFICATION_BADGES = exports.RATING = exports.REQUIRED_NIGHTS = exports.GUEST_LIMITS = exports.PRICE_RANGE = exports.PAGINATION = exports.DATETIME_FORMAT = exports.DATE_FORMAT = exports.CURRENCY = exports.COMMON_AMENITIES = exports.EMERGENCY_REASONS = exports.STAY_PURPOSES = exports.PROPERTY_TYPES = exports.INDIAN_STATES = exports.INDIAN_CITIES = void 0;
exports.INDIAN_CITIES = [
    'Jaipur',
    'Udaipur',
    'Jodhpur',
    'Kota',
    'Ajmer',
    'Bikaner',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
    'Tonk',
    'Sawai Madhopur',
    'Bhilwara',
    'Nagaur',
    'Chittorgarh',
    'Jhunjhunu',
    'Dausa',
    'Karauli',
    'Dholpur',
    'Baran',
    'Jaisalmer',
    'Barmer',
    'Jalore',
    'Sirohi',
    'Dungarpur',
    'Banswara',
    'Pratapgarh',
    'Rajsamand',
    'Bundi',
    'Agra',
    'Varanasi',
    'Lucknow',
    'Kanpur',
    'Prayagraj',
    'Gorakhpur',
    'Meerut',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Noida',
    'Ghaziabad',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Shahjahanpur',
    'Ayodhya',
    'Rampur',
    'Hapur',
    'Etawah',
    'Mirzapur',
    'Bulandshahr',
    'Sambhal',
    'Amroha',
    'Hardoi',
    'Farrukhabad',
    'Unnao',
    'Sitapur',
    'Lakhimpur',
    'Faizabad',
    'Gonda',
    'Bahraich',
    'Basti',
    'Deoria',
    'Ballia',
    'Azamgarh',
    'Mau',
    'Jaunpur',
    'Ghazipur',
    'Chandauli',
    'Bhadohi',
    'Sonbhadra',
    'Maharajganj',
    'Kushinagar',
    'Siddharthnagar',
    'Sant Kabir Nagar',
    'Ambedkar Nagar',
    'Amethi',
    'Hathras',
    'Kasganj',
    'Shamli',
    'Baghpat',
    'Indore',
    'Bhopal',
    'Jabalpur',
    'Gwalior',
    'Ujjain',
    'Sagar',
    'Ratlam',
    'Satna',
    'Rewa',
    'Murwara',
    'Singrauli',
    'Burhanpur',
    'Khandwa',
    'Bhind',
    'Mandsaur',
    'Neemuch',
    'Vidisha',
    'Hoshangabad',
    'Sehore',
    'Betul',
    'Chhindwara',
    'Damoh',
    'Katni',
    'Shivpuri',
    'Morena',
    'Datia',
    'Guna',
    'Ashoknagar',
    'Alirajpur',
    'Anuppur',
    'Balaghat',
    'Barwani',
    'Chhatarpur',
    'Dhar',
    'Dindori',
    'Jhabua',
    'Mandla',
    'Narsinghpur',
    'Niwari',
    'Panna',
    'Raisen',
    'Rajgarh',
    'Seoni',
    'Shahdol',
    'Sheopur',
    'Shajapur',
    'Sidhi',
    'Tikamgarh',
    'Umaria',
];
exports.INDIAN_STATES = [
    'Rajasthan',
    'Uttar Pradesh',
    'Madhya Pradesh',
    'Maharashtra',
    'Gujarat',
    'Karnataka',
    'Tamil Nadu',
    'Andhra Pradesh',
    'Telangana',
    'Kerala',
    'West Bengal',
    'Odisha',
    'Bihar',
    'Jharkhand',
    'Punjab',
    'Haryana',
    'Himachal Pradesh',
    'Uttarakhand',
    'Assam',
    'Chhattisgarh',
];
exports.PROPERTY_TYPES = [
    { value: 'ENTIRE_HOME', label: 'Entire Home' },
    { value: 'PRIVATE_ROOM', label: 'Private Room' },
    { value: 'SHARED_ROOM', label: 'Shared Room' },
    { value: 'GUEST_HOUSE', label: 'Guest House' },
    { value: 'HOMESTAY', label: 'Homestay' },
];
exports.STAY_PURPOSES = [
    { value: 'TOURISM', label: 'Tourism' },
    { value: 'HOSPITAL_VISIT', label: 'Hospital Visit' },
    { value: 'EMERGENCY', label: 'Emergency' },
    { value: 'EXAM', label: 'Exam' },
    { value: 'WEDDING', label: 'Wedding' },
    { value: 'PILGRIMAGE', label: 'Pilgrimage' },
    { value: 'BUSINESS', label: 'Business' },
    { value: 'FAMILY_VISIT', label: 'Family Visit' },
    { value: 'OTHER', label: 'Other' },
];
exports.EMERGENCY_REASONS = [
    { value: 'HOSPITAL', label: 'Hospital' },
    { value: 'FAMILY_EMERGENCY', label: 'Family Emergency' },
    { value: 'UNEXPECTED_TRAVEL', label: 'Unexpected Travel' },
    { value: 'OTHER', label: 'Other' },
];
exports.COMMON_AMENITIES = [
    'WiFi',
    'Air Conditioning',
    'Heating',
    'Kitchen',
    'Washing Machine',
    'TV',
    'Parking',
    'Hot Water',
    'Refrigerator',
    'Microwave',
    'Iron',
    'Hair Dryer',
    'Essentials (towels, bed sheets, soap)',
    'Workspace',
    'Crib',
    'High Chair',
    'Fire Extinguisher',
    'Smoke Alarm',
    'Carbon Monoxide Alarm',
    'First Aid Kit',
    'Security Cameras',
    'Lock on Bedroom Door',
    'Private Entrance',
    'Balcony',
    'Garden',
    'Pool',
    'Gym',
    'Elevator',
    'Wheelchair Accessible',
];
exports.CURRENCY = {
    code: 'INR',
    symbol: '₹',
    locale: 'en-IN',
};
exports.DATE_FORMAT = 'YYYY-MM-DD';
exports.DATETIME_FORMAT = 'YYYY-MM-DD HH:mm';
exports.PAGINATION = {
    defaultPage: 1,
    defaultLimit: 12,
    maxLimit: 50,
};
exports.PRICE_RANGE = {
    min: 500,
    max: 10000,
    step: 500,
};
exports.GUEST_LIMITS = {
    min: 1,
    max: 10,
};
exports.REQUIRED_NIGHTS = {
    min: 1,
    max: 30,
};
exports.RATING = {
    min: 1,
    max: 5,
};
exports.VERIFICATION_BADGES = {
    VERIFIED: 'verified',
    SUPERHOST: 'superhost',
    NEW: 'new',
};
//# sourceMappingURL=index.js.map